package com.nerdstore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-12-06T12:02:39.541-02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://das.ufsc.br/ConsultaCEP/", name = "ConsultaCEP")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaCEP {

    @WebMethod(action = "http://das.ufsc.br/ConsultaCEP/consultarCEP")
    @RequestWrapper(localName = "consultarCEP", targetNamespace = "http://das.ufsc.br/ConsultaCEP/", className = "com.nerdstore.ConsultarCEP")
    @ResponseWrapper(localName = "consultarCEPResponse", targetNamespace = "http://das.ufsc.br/ConsultaCEP/", className = "com.nerdstore.ConsultarCEPResponse")
    @WebResult(name = "informacaoCEP", targetNamespace = "")
    public com.nerdstore.InformacaoCEP consultarCEP(
        @WebParam(name = "cep", targetNamespace = "")
        java.lang.String cep,
        @WebParam(name = "Nome", targetNamespace = "")
        java.lang.String nome,
        @WebParam(name = "Email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "Cartao", targetNamespace = "")
        java.lang.String cartao,
        @WebParam(name = "CartaoVenc", targetNamespace = "")
        java.lang.String cartaoVenc,
        @WebParam(name = "qdtReatorArk", targetNamespace = "")
        java.lang.String qdtReatorArk,
        @WebParam(name = "qdtReatorSolar", targetNamespace = "")
        java.lang.String qdtReatorSolar,
        @WebParam(name = "qdtRoboMedico", targetNamespace = "")
        java.lang.String qdtRoboMedico,
        @WebParam(name = "qdtRoboSeguranca", targetNamespace = "")
        java.lang.String qdtRoboSeguranca,
        @WebParam(name = "qdtRoboDomestico", targetNamespace = "")
        java.lang.String qdtRoboDomestico
    );
}
